#ifndef ISEC_DATAENDPOINT_H
#define ISEC_DATAENDPOINT_H

#include <stdint.h>
#include <unistd.h>

#include "defaults.h"

typedef struct data_endpoint {
  pid_t pid;

  int   tun_fd;

  int   udp_sock;
  int   udp_port;

  int   write_fd;
  int   read_fd;

  unsigned char key[IVPN_KEY_LENGTH];

  /* peer end point parameters */
  int   peer_ip; // in network byte order generated by inet_aton()
  int   peer_port;

} data_endpoint_t;

data_endpoint_t *
start_data_endpoint();

#endif // ISEC_DATAENDPOINT_H
